version: "3"

services:
  localstack:
    image: localstack/localstack:0.12.12
    ports:
      - "4566-4597:4566-4597"
    environment:
      - SERVICES=sqs,sns,iam,s3,lambda
      - AWS_DEFAULT_REGION=us-east-2
      - EDGE_PORT=4566
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
